apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuma-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: kuma-pv
